### ISSUE TITLE
Ubuntu 16.04 x86_64 compile with Inform 7 build 6M62 crash 38% (Binding rulebooks)

### ISSUE THREAD

**Issue by RoundSparrow** [i7/counterfeit-monkey#58]
I know this issue is with the NI compiler, but figured worth noting here because other (smaller) stories seem to compile fine on the same system.  I've reproduced this on two different computers.  If anyone knows a work around please let me know.

++ 38% (Binding rulebooks)
*** glibc detected *** /usr/lib/x86_64-linux-gnu/gnome-inform7/ni: double free or corruption (out): 0x000000000ef89630 ***
======= Backtrace: =========
[0x5a5b92]
[0x5aa777]
[0x417a39]
[0x47982a]
[0x479181]
[0x513e2b]
[0x515b89]
[0x54f94b]
[0x54d0d4]
[0x598858]
[0x59bc13]
[0x400429]
======= Memory map: ========
00400000-006e5000 r-xp 00000000 08:03 512313                             /usr/lib/x86_64-linux-gnu/gnome-inform7/ni
008e5000-008e9000 rw-p 002e5000 08:03 512313                             /usr/lib/x86_64-linux-gnu/gnome-inform7/ni
008e9000-0090a000 rw-p 00000000 00:00 0 
01f1a000-0f3bf000 rw-p 00000000 00:00 0                                  [heap]
7f022c000000-7f022c021000 rw-p 00000000 00:00 0 
7f022c021000-7f0230000000 ---p 00000000 00:00 0 
7f0230d99000-7f0237539000 rw-p 00000000 00:00 0 
7f02389d3000-7f0238f87000 rw-p 00000000 00:00 0 
7f0238f88000-7f023901b000 rw-p 00000000 00:00 0 
7f0239388000-7f02393f3000 rw-p 00000000 00:00 0 
7fff6c57d000-7fff6c5de000 rw-p 00000000 00:00 0                          [stack]
7fff6c5fa000-7fff6c5fc000 r--p 00000000 00:00 0                          [vvar]
7fff6c5fc000-7fff6c5fe000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

**Comment by angstsmurf** [comment]
The current code builds fine for me on OS X and Windows. Have you tried raising the size adjustments in story.ni (Chapter 2 - Size Adjustments)?

**Comment by angstsmurf** [comment]
The compiler used to crash in the binding rulebooks stage due to a conflict between Locksmith and Facing. Make sure that you are using the right versions. 

That crash was triggered by both extensions declaring Constant SEQUENTIAL_ACTION, see http://inform7.com/mantis/view.php?id=1838

**Comment by RoundSparrow** [comment]
The Facing.i7x seems to suggest this was worked around:

Counterfeit Monkey.materials/Extensions/Emily Short/Facing.i7x:[Version 11/160611 Counterfeit Monkey version. Updated to work alongside Locksmith]

**Comment by angstsmurf** [comment]
Then it is probably caused by something else. Have you tried raising the memory settings, as suggested above? Does it generate any auto.inf I6 output in the Build directory?

**Comment by RoundSparrow** [comment]
"raising the memory settings," - I'm not sure what you mean precisely?

**Comment by angstsmurf** [comment]
In the file story.ni, there is a long list of memory settings for the compiler: 

```
Chapter 2 - Size Adjustments

Use ALLOC_CHUNK_SIZE of 64000.
Use MAX_ARRAYS of 60000.
Use MAX_CLASSES of 255.
Use MAX_VERBS of 510.
Use MAX_LABELS of 40000.
Use MAX_ZCODE_SIZE of 40000.
Use MAX_STATIC_DATA of 3000000.
```

And so on. You could try raising them all a bit. Unfortunately I'm no expert on this, so I can't tell you which one is most likely to cause problems.

**Comment by erkyrath** [comment]
Those memory settings are consumed by the I6 compiler. They don't affect ni (except that ni translates them into I6 directives), so they're not relevant here.

**Comment by erkyrath** [comment]
Someone on MacOS could try running the ni compile from the command line with malloc debugging. You turn on malloc debugging by setting environment variables:

    setenv DYLD_INSERT_LIBRARIES /usr/lib/libgmalloc.dylib
    setenv MALLOC_STRICT_SIZE 1

**Comment by angstsmurf** [comment]
This gives me:

> GuardMalloc[ni-701]: free: header for block 0x15ea87d2-0x15ea9000 has been trashed by a buffer underrun. Header magic value at 0x15ea87ce is 0x01adbeef, not 0xdeadbeef.  Try running with MALLOC_PROTECT_BEFORE to catch this error immediately as it happens.
> Abort trap: 6

**Comment by angstsmurf** [comment]
Setting export MALLOC_PROTECT_BEFORE=1 just gives me Bus error: 10.

**Comment by erkyrath** [comment]
That confirms that there is a bug in ni, at least.

I will try setting up the build on my home Mac and running it to get a stack trace out.

**Comment by erkyrath** [comment]
Filed as http://inform7.com/mantis/view.php?id=1948 .

**Comment by angstsmurf** [comment]
Fixed with #60 .

**Comment by RoundSparrow** [comment]
Did a fresh checkout into an empty directory and still get this problem:

*** glibc detected *** /usr/lib/x86_64-linux-gnu/gnome-inform7/ni: double free or corruption (out): 0x000000000e6c2190 ***
======= Backtrace: =========
[0x5a5b92]
[0x5aa777]
[0x417a39]
[0x47982a]
[0x479181]
[0x513e2b]
[0x515b89]
[0x54f94b]
[0x54d0d4]
[0x598858]
[0x59bc13]
[0x400429]
======= Memory map: ========
00400000-006e5000 r-xp 00000000 08:03 512313                             /usr/lib/x86_64-linux-gnu/gnome-inform7/ni
008e5000-008e9000 rw-p 002e5000 08:03 512313                             /usr/lib/x86_64-linux-gnu/gnome-inform7/ni
008e9000-0090a000 rw-p 00000000 00:00 0 
01653000-0eaf8000 rw-p 00000000 00:00 0                                  [heap]
7f37ac000000-7f37ac021000 rw-p 00000000 00:00 0 
7f37ac021000-7f37b0000000 ---p 00000000 00:00 0 
7f37b29ee000-7f37b9196000 rw-p 00000000 00:00 0 
7f37ba630000-7f37babe4000 rw-p 00000000 00:00 0 
7f37babe5000-7f37bac78000 rw-p 00000000 00:00 0 
7f37bafe5000-7f37bb050000 rw-p 00000000 00:00 0 
7ffe572b5000-7ffe57316000 rw-p 00000000 00:00 0                          [stack]
7ffe57345000-7ffe57347000 r--p 00000000 00:00 0                          [vvar]
7ffe57347000-7ffe57349000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

**Comment by angstsmurf** [comment]
My bad, I misunderstood @erkyrath . I assumed that "With this change, the game compiles out of the box on 6M62" in #60 meant that it compiled on Linux now. Apparently the problem still occurs.

**Comment by erkyrath** [comment]
Oh, sorry. My comment was misleading. I was just referring to the ability to get the thing built without "Missing extension" errors.

This bug is definitely an I7 compiler bug. I don't know if you want to track it here. There might be a workaround you can use in the CM code to avoid it, but I don't have any idea what that might be, if it's possible at all.

**Comment by angstsmurf** [comment]
Of course, it might still be an actual problem in our I7 code that triggers it. It is very similar to the crash caused by double Constant SEQUENTIAL_ACTION.

**Comment by erkyrath** [comment]
Possible, although I'm not sure about that particular connection.

**Comment by angstsmurf** [comment]
For what it is worth, I can get the current source to compile on Ubuntu Inform in VirtualBox now. I think it might have been 8516b4b that fixed it.

**Comment by curiousdannii** [comment]
Oh, that's good news, now we can make it run tests on Travis and upload a test build. 

Can you comment on the Inform bug highlighting what fixed it? Because there's still an underlying bug that needs to be fixed.

**Comment by angstsmurf** [comment]
[Done!](http://inform7.com/mantis/view.php?id=1948)

**Comment by angstsmurf** [comment]
Apparently I introduced this bug in 1f1880a . 

I probably changed subjects from things to objects while investigating [Mantis 0001921](http://inform7.com/mantis/view.php?id=1921) and forgot to change it back.

It is surprising that the code still worked as well as it did. Somewhat amusingly the commit has the comment "No doubt this huge change introduces new bugs".

**Comment by curiousdannii** [comment]
I'm not sure I'd call it a bug on our end - non model world entities should be able to be objects rather than things. It definitely shouldn't cause the compiler to crash. Once the compiler is fixed then we can re-evaluate what makes the code simplest and what gives the game the best performance.

**Comment by angstsmurf** [comment]
Yeah, I think this has something to do with the limits of relations in Inform ("relations aren't allowed to range over all 'objects' or all 'values', as these are too broad") and the fact that the mentioning relation relates quips both to subjects, which are abstract non model world entities, _and_ ordinary in-world things.
